### Make a Dictionary

In [133]:
dic = {"Name": ["Raj"], 
       "Location": ["Punjab"],
       "Score": [35]}
dic

{'Name': ['Raj'], 'Location': ['Punjab'], 'Score': [35]}

In [134]:
Nam = ["Kamal", "Bhaskar", "Gupta ji"]
Loc = ["Hisar","Ballabhgarh","Gurgaon"]
sco = [65,74,89] 

In [136]:
dic["Name"].extend(Nam)
dic

{'Name': ['Raj', 'Kamal', 'Bhaskar', 'Gupta ji'],
 'Location': ['Punjab'],
 'Score': [35]}

In [137]:
dic["Location"].extend(Loc)
dic["Score"].extend(sco)


In [138]:
dic

{'Name': ['Raj', 'Kamal', 'Bhaskar', 'Gupta ji'],
 'Location': ['Punjab', 'Hisar', 'Ballabhgarh', 'Gurgaon'],
 'Score': [35, 65, 74, 89]}

In [73]:
type(dic)

dict

In [56]:
Nam1 = ["Kamal", "Bhaskar", "Gupta ji"]
Loc1 = ["Hisar","Ballabhgarh","Gurgaon"]
sco1 = [65,74,89] 

In [61]:
dic1 = dict(zip(Nam1,Loc1))
dic1

{'Kamal': 'Hisar', 'Bhaskar': 'Ballabhgarh', 'Gupta ji': 'Gurgaon'}

In [1]:
fruits = ['apple', 'banana', 'orange']
prices = [1.0, 1.5, 2.0]
quantities = [10, 15, 20]

combined = list(zip(fruits, prices, quantities))
print(combined)
my_dict = dict(combined)

print(my_dict)


[('apple', 1.0, 10), ('banana', 1.5, 15), ('orange', 2.0, 20)]


ValueError: dictionary update sequence element #0 has length 3; 2 is required

In [63]:
dic1


{'Kamal': 'Hisar', 'Bhaskar': 'Ballabhgarh', 'Gupta ji': 'Gurgaon'}

In [75]:
dic2 = {"PinCode" : [252557,565687,412154,425789,]}

In [76]:
dic.update(dic2)

In [77]:
dic

{'Name': ['Raj', 'Kamal', 'Bhaskar', 'Gupta ji'],
 'Location': ['Punjab', 'Hisar', 'Ballabhgarh', 'Gurgaon'],
 'Score': [35, 65, 74, 89],
 'PinCode': [252557, 565687, 412154, 425789]}

## Sort an Array

In [78]:
x = [1,2,5,87,9,5,8,4,6,23,5,8]
x

[1, 2, 5, 87, 9, 5, 8, 4, 6, 23, 5, 8]

In [81]:
# soritng of Array in Ascending Order
for i in range(len(x)):
    for j in range(i+1, len(x)):
        if x[i] > x[j]:
            x[i],x[j] =x[j],x[i]
print(x)

[1, 2, 4, 5, 5, 5, 6, 8, 8, 9, 23, 87]


In [99]:
# soritng of Array in Descsnding Order
def sorR(x):
    for i in range(len(x)):
        for j in range(i+1, len(x)):
            if x[i] < x[j]:
                x[i],x[j] = x[j],x[i]


In [101]:
x = [1,2,5,87,9,5,8,4,6,23,5,8]
sorR(x)
print(x)

[87, 23, 9, 8, 8, 6, 5, 5, 5, 4, 2, 1]


### Reverse an String

In [105]:
x = "Vipin Saini"

rev= ""
for i in range(len(x)-1,-1,-1):
    rev+=x[i]
print(rev)
    

iniaS nipiV


In [19]:
x = "Vipin Saini"
y = x.split(" ")
print(y)
print(y[::-1])

['Vipin', 'Saini']
['Saini', 'Vipin']


In [20]:
x = "Vipin Saini"
x[::-1]


'iniaS nipiV'

In [26]:
x = "Vipin Saini"
y = x.split(" ")
y = y[::-1]
y = " ".join(y)
y

'Saini Vipin'

### Index No.

In [121]:
x = [87,9,5,8,4,6,23,5,8]

In [122]:
for index,values in enumerate(x):
    print(index,values)

0 87
1 9
2 5
3 8
4 4
5 6
6 23
7 5
8 8


In [2]:
import pandas as pd
import numpy as  np

In [125]:
y = pd.Series(x)

In [126]:
df = pd.Series(y)

In [128]:
df.value_counts()

5     2
8     2
87    1
9     1
4     1
6     1
23    1
dtype: int64

In [129]:
from collections import Counter

In [132]:
Counter(x)

Counter({87: 1, 9: 1, 5: 2, 8: 2, 4: 1, 6: 1, 23: 1})

### Sort the Dictionary in Ascending Order through Values

In [143]:
lst1 = ["A","D","B","C","T"]
lst2 = [2,4,8,75,6]

In [144]:
dit = dict(zip(lst1,lst2))
dit

{'A': 2, 'D': 4, 'B': 8, 'C': 75, 'T': 6}

In [149]:
sort = dict(sorted(dit.items(), key = lambda x:x[1]))
sort

{'A': 2, 'D': 4, 'T': 6, 'B': 8, 'C': 75}

### Sort the Dictionary in Ascending Order through Keys

In [150]:
sort = dict(sorted(dit.items()))
sort

{'A': 2, 'B': 8, 'C': 75, 'D': 4, 'T': 6}

### Sort the Dictionary in Descending Order through Keys

In [151]:
sort = dict(sorted(dit.items(), reverse = True))
sort

{'T': 6, 'D': 4, 'C': 75, 'B': 8, 'A': 2}

### Empty Array

In [154]:
x = np.zeros(5,int)
x

array([0, 0, 0, 0, 0])

In [155]:
x[2] = 5
x

array([0, 0, 5, 0, 0])

In [156]:
x = np.random.rand(2,5)
x

array([[0.01537018, 0.79854675, 0.36743878, 0.77230883, 0.70512396],
       [0.87762598, 0.28169666, 0.86562425, 0.19204888, 0.96201669]])

In [164]:
x = np.random.randint(2,5)
x

2

In [166]:
x = np.random.randint(2,5, size =(5))
x

array([4, 4, 3, 4, 4])

In [168]:
x = np.random.randint(2,5, size =(4,4))
x

array([[3, 2, 2, 4],
       [4, 4, 3, 2],
       [2, 3, 3, 4],
       [3, 4, 2, 3]])

In [167]:
np.sort(x)

array([3, 4, 4, 4, 4])

In [169]:
y = np.linalg.det(x)
y

31.0

In [170]:
y = np.linalg.inv(x)
y

array([[ 0.41935484,  0.25806452, -0.4516129 , -0.12903226],
       [-0.38709677, -0.16129032,  0.03225806,  0.58064516],
       [-0.19354839,  0.41935484,  0.51612903, -0.70967742],
       [ 0.22580645, -0.32258065,  0.06451613,  0.16129032]])

### Create a 3x3 matrix with values ranging from 0 to 8

In [173]:
x = np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [174]:
np.flip(x, axis = 0)

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [175]:
np.flip(x, axis = 1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [176]:
x = np.array([[2,5],[8,7]])
x

array([[2, 5],
       [8, 7]])

In [180]:
x = np.random.randint(2,9, size =(6))
x

array([7, 7, 3, 5, 8, 2])

In [182]:
x[x.argmax()] = 15
x

array([ 7,  7,  3,  5, 15,  2])

In [228]:
x = {'Week Day': ['Mon', 'Tue', 'Wed','Thu', 'Fri'],
     'Subject': ['Chemisry','Physics','Maths','English','Biology'],
     'Time': ['2 PM', '10 AM', '11 AM','1 PM', '3 PM']}
x

{'Week Day': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
 'Subject': ['Chemisry', 'Physics', 'Maths', 'English', 'Biology'],
 'Time': ['2 PM', '10 AM', '11 AM', '1 PM', '3 PM']}

In [229]:
df = pd.DataFrame(x)
df

Week Day   Subject   Time
0      Mon  Chemisry   2 PM
1      Tue   Physics  10 AM
2      Wed     Maths  11 AM
3      Thu   English   1 PM
4      Fri   Biology   3 PM

In [230]:
df["Weekend"] = pd.Series([5,8,7])
df

Week Day   Subject   Time  Weekend
0      Mon  Chemisry   2 PM      5.0
1      Tue   Physics  10 AM      8.0
2      Wed     Maths  11 AM      7.0
3      Thu   English   1 PM      NaN
4      Fri   Biology   3 PM      NaN

In [231]:
df.rename({"Subject": "sub"},axis = 1)

Week Day       sub   Time  Weekend
0      Mon  Chemisry   2 PM      5.0
1      Tue   Physics  10 AM      8.0
2      Wed     Maths  11 AM      7.0
3      Thu   English   1 PM      NaN
4      Fri   Biology   3 PM      NaN

In [232]:
df.rename({0: "Hero"}, axis = 0)

Week Day   Subject   Time  Weekend
Hero      Mon  Chemisry   2 PM      5.0
1         Tue   Physics  10 AM      8.0
2         Wed     Maths  11 AM      7.0
3         Thu   English   1 PM      NaN
4         Fri   Biology   3 PM      NaN

In [233]:
df.to_numpy()

array([['Mon', 'Chemisry', '2 PM', 5.0],
       ['Tue', 'Physics', '10 AM', 8.0],
       ['Wed', 'Maths', '11 AM', 7.0],
       ['Thu', 'English', '1 PM', nan],
       ['Fri', 'Biology', '3 PM', nan]], dtype=object)

In [194]:
df.to_numpy().tolist()

[['Mon', 'Chemisry', '2 PM', 5.0],
 ['Tue', 'Physics', '10 AM', 8.0],
 ['Wed', 'Maths', '11 AM', 7.0],
 ['Thu', 'English', '1 PM', nan],
 ['Fri', 'Biology', '3 PM', nan]]

In [234]:
df

Week Day   Subject   Time  Weekend
0      Mon  Chemisry   2 PM      5.0
1      Tue   Physics  10 AM      8.0
2      Wed     Maths  11 AM      7.0
3      Thu   English   1 PM      NaN
4      Fri   Biology   3 PM      NaN

In [199]:
df1 = df.groupby(["Subject","Weekend"]).size().reset_index()
df1

Subject  Weekend  0
0  Chemisry      5.0  1
1     Maths      7.0  1
2   Physics      8.0  1

In [200]:
df1.drop(0, axis = 1)

Subject  Weekend
0  Chemisry      5.0
1     Maths      7.0
2   Physics      8.0

In [201]:
df

Week Day   Subject   Time  Weekend
0      Mon  Chemisry   2 PM      5.0
1      Tue   Physics  10 AM      8.0
2      Wed     Maths  11 AM      7.0
3      Thu   English   1 PM      NaN
4      Fri   Biology   3 PM      NaN

In [235]:
df["Weekend"].median()

7.0

In [236]:
df["Weekend"] = df["Weekend"].fillna(df["Weekend"].median())
df

Week Day   Subject   Time  Weekend
0      Mon  Chemisry   2 PM      5.0
1      Tue   Physics  10 AM      8.0
2      Wed     Maths  11 AM      7.0
3      Thu   English   1 PM      7.0
4      Fri   Biology   3 PM      7.0

In [237]:
df["Score"] = pd.Series([85,74,32])
df

Week Day   Subject   Time  Weekend  Score
0      Mon  Chemisry   2 PM      5.0   85.0
1      Tue   Physics  10 AM      8.0   74.0
2      Wed     Maths  11 AM      7.0   32.0
3      Thu   English   1 PM      7.0    NaN
4      Fri   Biology   3 PM      7.0    NaN

In [238]:
np.round(df["Score"].mean())

64.0

In [239]:
df["Score"] = np.where(df["Score"].isna(),np.round(df["Score"].mean()),df["Score"])
df

Week Day   Subject   Time  Weekend  Score
0      Mon  Chemisry   2 PM      5.0   85.0
1      Tue   Physics  10 AM      8.0   74.0
2      Wed     Maths  11 AM      7.0   32.0
3      Thu   English   1 PM      7.0   64.0
4      Fri   Biology   3 PM      7.0   64.0

In [225]:
x = np.random.randint(2,19,size = (4,6))
df = pd.DataFrame(x, index = list("ABCD"), columns = list("123456"))
df

1  2   3   4   5   6
A  18  6   3  12   4   6
B  10  2  10  11  10   6
C   7  4   8  16  17   4
D  11  4  16   3  18  11

In [227]:
df.apply(lambda x:x*5)

1   2   3   4   5   6
A  90  30  15  60  20  30
B  50  10  50  55  50  30
C  35  20  40  80  85  20
D  55  20  80  15  90  55

In [240]:
df

Week Day   Subject   Time  Weekend  Score
0      Mon  Chemisry   2 PM      5.0   85.0
1      Tue   Physics  10 AM      8.0   74.0
2      Wed     Maths  11 AM      7.0   32.0
3      Thu   English   1 PM      7.0   64.0
4      Fri   Biology   3 PM      7.0   64.0

In [243]:
df.sort_values("Subject", ascending = False)

Week Day   Subject   Time  Weekend  Score
1      Tue   Physics  10 AM      8.0   74.0
2      Wed     Maths  11 AM      7.0   32.0
3      Thu   English   1 PM      7.0   64.0
0      Mon  Chemisry   2 PM      5.0   85.0
4      Fri   Biology   3 PM      7.0   64.0

In [250]:
t = df["Time"].apply(lambda x:x.split(" "))
t

0     [2, PM]
1    [10, AM]
2    [11, AM]
3     [1, PM]
4     [3, PM]
Name: Time, dtype: object

In [276]:
x = []
for i in t:
    x.append(i[0])
print(x)

['2', '10', '11', '1', '3']


In [278]:
df = pd.DataFrame({"Name":["Ganesh Mahesh Patel","Sachin Ramesh Tendulkar"]}
                 )
df

Name
0      Ganesh Mahesh Patel
1  Sachin Ramesh Tendulkar

In [280]:
df["Name"].str.split(expand = True)

0       1          2
0  Ganesh  Mahesh      Patel
1  Sachin  Ramesh  Tendulkar

In [281]:
df1 = pd.DataFrame({"Player":["Virat","Rohit","KL Rahul","Sachin","Hardik","Dinesh"],
                   "Team":["RCB","MI","LSG","MI","DDD","KNR"],
                   "Avg":[45,39,34,46,55,88]})
df1

Player Team  Avg
0     Virat  RCB   45
1     Rohit   MI   39
2  KL Rahul  LSG   34
3    Sachin   MI   46
4    Hardik  DDD   55
5    Dinesh  KNR   88

In [282]:
df2 = {"Player":"Shami", "Team": "DDD","Avg": 22}
df2

{'Player': 'Shami', 'Team': 'DDD', 'Avg': 22}

In [290]:
df = df1.append(df2, ignore_index= True)
df

Player Team  Avg
0     Virat  RCB   45
1     Rohit   MI   39
2  KL Rahul  LSG   34
3    Sachin   MI   46
4    Hardik  DDD   55
5    Dinesh  KNR   88
6     Shami  DDD   22

In [292]:
df = pd.DataFrame({
'company_code': ['C-0001','C-0002','C-0003', 'C-0003', 'C-0004'],
'year': ['1800','1700','2300', '1900', '2200']
})
df

company_code  year
0       C-0001  1800
1       C-0002  1700
2       C-0003  2300
3       C-0003  1900
4       C-0004  2200

In [294]:
df[df["year"].between("1850","2250")]

company_code  year
3       C-0003  1900
4       C-0004  2200

In [316]:
df1 = pd.DataFrame({"Player":["Virat","Rohit","KL Rahul","Sachin"],
                   "Team":["RCB","MI","LSG","MI"],
                   "Avg":[45,39,34,46]})
df2 = pd.DataFrame({"Player":["AB","Pollard","De Cock","Moeeb Ali"],
                   "Team":["RCB","MI","LSG","CSK"],
                   "Avg":[5,38,41,47]})

In [317]:
df = pd.concat([df1,df2], axis = 0, ignore_index = True)
df

Player Team  Avg
0      Virat  RCB   45
1      Rohit   MI   39
2   KL Rahul  LSG   34
3     Sachin   MI   46
4         AB  RCB    5
5    Pollard   MI   38
6    De Cock  LSG   41
7  Moeeb Ali  CSK   47

In [314]:
df = pd.concat([df1,df2], axis = 1, ignore_index = True)
df

0    1   2          3    4   5
0     Virat  RCB  45         AB  RCB   5
1     Rohit   MI  39    Pollard   MI  38
2  KL Rahul  LSG  34    De Cock  LSG  41
3    Sachin   MI  46  Moeeb Ali  CSK  47

In [303]:
df1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
        'name': ['Rakesh', 'Vikram', 'Vedha', 'Saif', 'Hritik'], 
        'marks': [200, 210, 220, 230, 240]})

df2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Mady', 'Vijay', 'Abhishek', 'Dino', 'Kalia'], 
        'marks': [56, 62, 220, 84, 240]})


In [305]:
df= pd.merge(df1,df2, on = "student_id", how = "outer")
# df = pd.merge(df1,df2, on = "student_id", how = "inner")
df

student_id  name_x  marks_x    name_y  marks_y
0         S1  Rakesh    200.0       NaN      NaN
1         S2  Vikram    210.0       NaN      NaN
2         S3   Vedha    220.0       NaN      NaN
3         S4    Saif    230.0      Mady     56.0
4         S5  Hritik    240.0     Vijay     62.0
5         S6     NaN      NaN  Abhishek    220.0
6         S7     NaN      NaN      Dino     84.0
7         S8     NaN      NaN     Kalia    240.0

In [306]:
df1 = pd.DataFrame({"Player":["Virat","Rohit","KL Rahul","Sachin"],
                   "Team":["RCB","MI","LSG","MI"],
                   "Avg":[45,39,34,46]})
df2 = pd.DataFrame({"Player":["AB","Pollard","De Cock","Moeeb Ali"],
                   "Team":["RCB","MI","LSG","CSK"],
                   "Avg":[5,38,41,47]})

In [310]:
df= pd.merge(df1,df2, on = "Player", how = "outer")


In [311]:
df

Player Team_x  Avg_x Team_y  Avg_y
0      Virat    RCB   45.0    NaN    NaN
1      Rohit     MI   39.0    NaN    NaN
2   KL Rahul    LSG   34.0    NaN    NaN
3     Sachin     MI   46.0    NaN    NaN
4         AB    NaN    NaN    RCB    5.0
5    Pollard    NaN    NaN     MI   38.0
6    De Cock    NaN    NaN    LSG   41.0
7  Moeeb Ali    NaN    NaN    CSK   47.0

In [318]:
df

Player Team  Avg
0      Virat  RCB   45
1      Rohit   MI   39
2   KL Rahul  LSG   34
3     Sachin   MI   46
4         AB  RCB    5
5    Pollard   MI   38
6    De Cock  LSG   41
7  Moeeb Ali  CSK   47

In [325]:
df.loc[(df["Team"] == "RCB") |(df["Avg"] > 45)]

Player Team  Avg
0      Virat  RCB   45
3     Sachin   MI   46
4         AB  RCB    5
7  Moeeb Ali  CSK   47

In [326]:
df.loc[(df["Team"] == "RCB")]

Player Team  Avg
0  Virat  RCB   45
4     AB  RCB    5

In [327]:
df.loc[(df["Avg"] > 45)]

Player Team  Avg
3     Sachin   MI   46
7  Moeeb Ali  CSK   47

### Second Highest No from a List

In [ ]:
x = [10, 20, 5, 15, 30]

highest = x[0]
second_highest = x[0]

for i in x:
    if i > highest:
        second_highest = highest
        highest = i
    elif i > second_highest and i < highest:
        second_highest = i

print("The second highest number is:", second_highest)

In [337]:
x = [10, 20, 5, 15, 30]
x.sort(reverse = True)
x

[30, 20, 15, 10, 5]

In [338]:
x[1]

20

### Most repeated character in a String

In [328]:
def word_count(x):
    count = dict()
    y = x.split()
    for i in y:
        if  i in count:
            count[i] +=1
        else:
            count[i] =1
    count_x = sorted(count.items(), key = lambda t: t[1])
    return count_x[-1] # -2/-3/-4 etc...

print(word_count("Both of these issues are fixed by postponing the evaluation of annotations. Instead of compiling code which executes expressions in annotations at their definition time, the compiler stores the annotation in a string form equivalent to the AST of the expression in question. If needed, annotations can be resolved at runtime using typing.get_type_hints(). In the common case where this is not required, the annotations are cheaper to store (since short strings are interned by the interpreter) and make startup time faster."))

('the', 8)


In [349]:
def word_repeat(x):
    count = dict()
    y = x.split()
    for i in y:
        if i in count:
            count[i]+=1
        else:
            count[i] = 1
            
    counted = sorted(count.items(), key = lambda x:x[1])
    return counted

In [350]:
x = """ while working with Python dictionaries, we can have a problem in which we need to perform the sorting of it, wrt keys, but also can have a variation in which we need to perform a sort on its values list as well. Let’s discuss certain way in which this task can be performed."""
word_repeat(x)

[('while', 1),
 ('working', 1),
 ('with', 1),
 ('Python', 1),
 ('dictionaries,', 1),
 ('problem', 1),
 ('the', 1),
 ('sorting', 1),
 ('of', 1),
 ('it,', 1),
 ('wrt', 1),
 ('keys,', 1),
 ('but', 1),
 ('also', 1),
 ('variation', 1),
 ('sort', 1),
 ('on', 1),
 ('its', 1),
 ('values', 1),
 ('list', 1),
 ('as', 1),
 ('well.', 1),
 ('Let’s', 1),
 ('discuss', 1),
 ('certain', 1),
 ('way', 1),
 ('this', 1),
 ('task', 1),
 ('be', 1),
 ('performed.', 1),
 ('have', 2),
 ('need', 2),
 ('to', 2),
 ('perform', 2),
 ('we', 3),
 ('can', 3),
 ('a', 3),
 ('in', 3),
 ('which', 3)]

### Prime No.

In [358]:
n = 17

for i in range(2,n):
    if n%i == 0:
        print(F"{n} is not a Prime No")
        break
else:
    print(F"{n} is a Prime No")


17 is a Prime No


### Factorial

In [3]:
def fact(n):
    if n == 0:
        return 1
    else:
        return n * fact(n-1)
fact(5)

120

### Fibonnia Series

In [10]:
n = 6
first = 0
second = 1

print(first)
print(second)

for i in range(0,n-2):
    new = first+second
    first = second
    second = new
    print(new)

0
1
1
2
3
5


### Python code to remove duplicate elements

In [11]:
x = [2, 4, 10, 20, 5, 2, 20, 4]

dup = []
for i in x:
    if i not in dup:
        dup.append(i)
print(dup)

[2, 4, 10, 20, 5]


In [12]:
set(x)

{2, 4, 5, 10, 20}

### Write the code to check whether the given string is palindrome or not

In [13]:
def rev(x):
    if x ==x[::-1]:
        print("Its a Palindrome")
    else:
        print("Its not a Palindrome")
    

In [14]:
x = "Vipin"
rev(x)

Its not a Palindrome


In [15]:
x = "civic"
rev(x)

Its a Palindrome


In [ ]:
x  = "Sky is blue"
x.splt()

In [3]:
x = {"Salary":['200','500','754','651','105','976','248','325','554','677'],
     "Marks":['85','20','35','95','68','75','41','23','36','85']}
df = pd.DataFrame(x)

In [4]:
df["Marks"].unique

<bound method Series.unique of 0    85
1    20
2    35
3    95
4    68
5    75
6    41
7    23
8    36
9    85
Name: Marks, dtype: object>

In [5]:
df

Salary Marks
0    200    85
1    500    20
2    754    35
3    651    95
4    105    68
5    976    75
6    248    41
7    325    23
8    554    36
9    677    85

In [6]:
df["Class"]  =pd.Series([85,54,56,52,58,7,4,56])
df

Salary Marks  Class
0    200    85   85.0
1    500    20   54.0
2    754    35   56.0
3    651    95   52.0
4    105    68   58.0
5    976    75    7.0
6    248    41    4.0
7    325    23   56.0
8    554    36    NaN
9    677    85    NaN

In [7]:
mr = [0,20,40,60,80,100]
gp_name = ["Very_Poor","Poor","Average","Good","Brilliant"]
df["Category"] = pd.cut(df["Marks"], mr, labels = gp_name)

TypeError: '<' not supported between instances of 'int' and 'str'

### Write a program to print every character of a string entered by the user in a new line using a loop?

In [9]:
x = input("Enter your Name ")

for i in x:
    print(i)

Enter your Name Vipin
V
i
p
i
n


### Write a program to find the length of the string "machine learning" with and without using len function

In [10]:
x = "Machine Learning"
len(x)

16

In [12]:
count = 0
for i in x:
    count+=1
print(count)    

16


### Write a program to check if the word 'orange' is present in the "This is orange juice"

In [13]:
x = "This is orange juice"

"orange" in x

True

### Write a program to find the number of vowels, consonants, digits, and white space characters in a string

In [15]:
x = """Data science is a field that studies data and how to extract meaning from it,
       whereas machine learning is a field devoted to understanding and building methods 
       that utilize data to improve performance or inform predictions."""
       
x

'Data science is a field that studies data and how to extract meaning from it,\n       whereas machine learning is a field devoted to understanding and building methods \n       that utilize data to improve performance or inform predictions.'

In [16]:
vo = 'aeiou'
co = 'bcdfghjklmnpqrstvwxyz'
di = '0123456789'
wp = " "

v = 0
c = 0
d = 0
w_ = 0

for i in x:
    if i in vo:
        v+=1
    elif i in co:
        c+=1
    elif i in di:
        d+=1
    else:
        w_+=1
print(v)
print(c)
print(d)
print(w_)
        

74
111
0
53


In [18]:
vo = 'aeiou'
co = 'bcdfghjklmnpqrstvwxyz'
di = '0123456789'
wp = " "

v = []
c = []
d = []
w_ = []

for i in x:
    if i in vo:
        v.append(i)
        
    elif i in co:
        c.append(i)
    elif i in di:
        d.append(i)
    else:
        w_.append(i)
print(v)
print(c)
print(d)
print(w_)
        

['a', 'a', 'i', 'e', 'e', 'i', 'a', 'i', 'e', 'a', 'u', 'i', 'e', 'a', 'a', 'a', 'o', 'o', 'e', 'a', 'e', 'a', 'i', 'o', 'i', 'e', 'e', 'a', 'a', 'i', 'e', 'e', 'a', 'i', 'i', 'a', 'i', 'e', 'e', 'o', 'e', 'o', 'u', 'e', 'a', 'i', 'a', 'u', 'i', 'i', 'e', 'o', 'a', 'u', 'i', 'i', 'e', 'a', 'a', 'o', 'i', 'o', 'e', 'e', 'o', 'a', 'e', 'o', 'i', 'o', 'e', 'i', 'i', 'o']
['t', 's', 'c', 'n', 'c', 's', 'f', 'l', 'd', 't', 'h', 't', 's', 't', 'd', 's', 'd', 't', 'n', 'd', 'h', 'w', 't', 'x', 't', 'r', 'c', 't', 'm', 'n', 'n', 'g', 'f', 'r', 'm', 't', 'w', 'h', 'r', 's', 'm', 'c', 'h', 'n', 'l', 'r', 'n', 'n', 'g', 's', 'f', 'l', 'd', 'd', 'v', 't', 'd', 't', 'n', 'd', 'r', 's', 't', 'n', 'd', 'n', 'g', 'n', 'd', 'b', 'l', 'd', 'n', 'g', 'm', 't', 'h', 'd', 's', 't', 'h', 't', 't', 'l', 'z', 'd', 't', 't', 'm', 'p', 'r', 'v', 'p', 'r', 'f', 'r', 'm', 'n', 'c', 'r', 'n', 'f', 'r', 'm', 'p', 'r', 'd', 'c', 't', 'n', 's']
[]
['D', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',

### Write a program to make a new string with all the consonants deleted from the string "Hello, have a good day"

In [21]:
x = "Hello, have a good day"

v = 'aeiouAEIOU'
y = []

for i in x:
    if i not in v:
        y.append(i)
y = " ".join(y)
y

'H l l ,   h v     g d   d y'

### Write a Python program to remove the nth index character from a non-empty string

In [27]:
x = "Hello, have a good day"
n = 2
x = x.replace(x[n], " ")
x

'He  o, have a good day'

### Write a Python program to change a given string to a new string where the first and last characters have been exchanged

In [31]:
x = "We are Data Scientist"
print(x)

y = x[-1] + x[1:len(x)-1] +x[0]
y

We are Data Scientist


'te are Data ScientisW'

In [35]:
rev = " "
for i in range(len(x)-1,-1,-1):
    rev+= x[i]
    
print(rev)

 tsitneicS ataD era eW


## Convert to Upper Case

In [37]:
x = """DATa science is a field that studies data"""
x.upper()

'DATA SCIENCE IS A FIELD THAT STUDIES DATA'

### Write a Python program to find the first repeated character in a given string

In [46]:
def rep(x):
    count = dict()
    for i in x:
        if i in count:
            count[i]+=1
        else:
            count[i]=1
    counted = sorted(count.items(), key = lambda b:b[1])
    return counted[-2]

In [47]:
x = """DATa science is a field that studies data"""
rep(x)


('a', 5)

In [50]:
def rep(x):
    count = dict()
    y = x.split()
    for i in y:
        if i in count:
            count[i]+=1
        else:
            count[i]=1
    counted = sorted(count.items(), key = lambda b:b[1])
    return counted[-2]

In [51]:
rep("Note that the number of categories should be one less than the number of cut-off values in mr, since the first category includes values from 0 up to the first cut-off value, and the last category includes values from the last cut-off value up to infinity.")

('values', 3)

### Python program to Count Even and Odd numbers in a string

In [52]:
even = 0
odd = 0

for i in range(1,51):
    if i%2 == 0:
        even+=1
    else:
        odd+=1
print(even)
print(odd)

25
25


In [53]:
even = []
odd = []

for i in range(1,51):
    if i%2 == 0:
        even.append(i)
    else:
        odd.append(i)
print(even)
print(odd)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


### Write a Python program to reverse words in a string?

In [54]:
x = "This is Machine Learning & Python"
x[::-1]

'nohtyP & gninraeL enihcaM si sihT'

In [56]:
y = x.split(" ")
y[::-1]

['Python', '&', 'Learning', 'Machine', 'is', 'This']

In [57]:
rev = ""
for i in range(len(x)-1,-1,-1):
    rev+=x[i]
print(rev)

nohtyP & gninraeL enihcaM si sihT


### Write a Python program to remove duplicate characters of a given string

In [66]:
x = "Hi this is Machine Learning & this is Python"

dup = ""

for i in x:
    if i not in dup:
        dup+=i
print(dup)


Hi thsMacneLrg&Pyo


In [65]:
z = set(x)
print(z, end = "")

{'s', 'r', 'g', 'L', 'T', 'h', 'n', 'a', 'M', 'P', ' ', 'e', '&', 'y', 'o', 'i', 't', 'c'}

### Python Program to find Sum of squares of first n natural numbers

In [68]:
n = 3
sum1 = 0

for i in range(1,n+1):
    sum1+= i**2
print(sum1)

14


### Write a Python program to generate all sublists of a list?

In [70]:
x = [3,4,5,7,3,2,1,6,8,9]

for i in x:
    print([i], end = "")
    

[3][4][5][7][3][2][1][6][8][9]

### Sort a List

In [75]:
x = [8,6,7,9,5,4]

for i in range(len(x)):
    for j in range(i+1, len(x)):
        if x[i] < x[j]:
            x[i],x[j] = x[j],x[i]
print(x)

[9, 8, 7, 6, 5, 4]


In [81]:
sorted(x)

[4, 5, 6, 7, 8, 9]

In [84]:
a = (3,4,5,6,7,3)
ls = list(a)
x = sorted(ls)
x

[3, 3, 4, 5, 6, 7]

In [85]:
b = tuple(x)

In [86]:
b

(3, 3, 4, 5, 6, 7)

### Flatten a List

In [89]:
list1 = [[1], [2, 3], [4, 5], [6, 7]]

x = []
for i in list1:
    for j in i:
        x.append(j)
print(x)

[1, 2, 3, 4, 5, 6, 7]


### Write a Python program to find square and cube every number in a given list of

In [90]:
num = [1, 2, 3, 4, 5]

squred_Cubed = list(map(lambda x:(x**2, x**3), num))
squred_Cubed

[(1, 1), (4, 8), (9, 27), (16, 64), (25, 125)]